### PR TITLE
DeepL interpolation bad output

### PR DESCRIPTION
**Pull request by stefan-lacatus**
## Intent

- resolve cases where DeepL generates translated tokens that contain something like `<span ???=\"no\"> ....`

### Actual fix
`json-autotranslate` replaces the interpolation from i18next (and I assume others) with `<span translate="no">${index}</span>`, and in rare cases DeepL ends up translating this section as well.
By properly informing DeepL about the types of tags we are sending, avoid the issue. See https://www.deepl.com/docs-api/html/disabling
Example of text that had issues:

 from EN to PL
```
Recurring - Every {{message}} cycles
----- translates to
Powtarzające się - co <span translate=\"no\">0 cykli</span>.
```

### Combining the free and paid API implementations

I noticed this in #97, but did not properly investigated it then. 

The `deepl-free.ts` was almost identical to `deepl.ts`. This merges the two into one. End-users should not be impacted by this change.

### CODE REVIEW

**Review by leolabs — APPROVED** [review]
That looks great, thank you for the fix!

**Comment by stefan-lacatus** [comment]
Thanks a lot for the quick merging!

It looks like the version numbers got a bit messed up as v1.12.0 contained (#97), released earlier today and v11.1.0 containing this PR, was released just now.

See https://www.npmjs.com/package/json-autotranslate?activeTab=versions, https://github.com/leolabs/json-autotranslate/releases

**Comment by leolabs** [comment]
Good catch! I released v1.12.1 which is the same as v1.11.1 though I don't think I can remove the invalid older version.

**Comment by stefan-lacatus** [comment]
> Good catch! I released v1.12.1 which is the same as v1.11.1 though I don't think I can remove the invalid older version.

Thanks! I see v1.12.1 released on github, but not on npm. Can you push it to there as well?

**Comment by leolabs** [comment]
You're right, somehow the release tool I'm using seems to be flaky at the moment. I've just pushed the version to NPM!

**Pull request merged**
